# these are the different stages for our pipelines
# jobs in the same stage run in parallel 
# next stage doesn't start until previous stage finishes with 'OK'
# by now we only do build and test, we could add another stage "deploy" if
# needed
stages:
  - test

# Ubuntu22.04 STAGE
test:ubuntu22.04:
  stage: test
  image:
    name: ubuntu:22.04
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  before_script:
    - echo "Running ubuntu22.04 'before_script'..."
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 871920D1991BC93C
    - apt-get update -y
    - echo "... done running ubuntu22.04 'before_script'."
  script:
  - echo "Testing on Ubuntu 22.04..."
  - echo "... done testing on Ubuntu 22.04."
